name: AdminHax
version: '${project.version}'
main: simplexity.adminhax.AdminHax
api-version: '1.20'
commands:
  flyspeed:
    permission: adminhax.commands.speed.fly
    description: allows you to change your walk speed
    usage: /<command> [set|get|reset] <speed>
    aliases: [fs]
  walkspeed:
    permission: adminhax.commands.speed.walk
    description: allows you to change your walk speed
    usage: /<command> [set|get|reset] <speed>
    aliases: [ ws ]
  fly:
    permission: adminhax.commands.fly
    description: allows you to fly
    usage: /<command>
  feed:
    permission: adminhax.commands.feed
    description: allows you to feed
    usage: /<command>
  heal:
    permission: adminhax.commands.heal
    description: allows you to heal
    usage: /<command>
  repair:
    permission: adminhax.commands.repair
    description: allows you to repair
    usage: /<command> [hand|hotbar|inventory|armor|all]
  godmode:
    permission: adminhax.commands.godmode
    description: allows you to godmode
    usage: /<command> [get|toggle] <player>
permissions:
  adminhax.commands.speed.walk:
    default: op
    description: allows you to change your walk speed
  adminhax.commands.other.speed.walk:
    default: op
    description: allows you to change your walk speed
  adminhax.commands.speed.fly:
    default: op
    description: allows you to change your walk speed
  adminhax.commands.other.speed.fly:
    default: op
    description: allows you to change your walk speed
  adminhax.commands.fly:
    default: op
    description: allows you to fly
  adminhax.commands.other.fly:
    default: op
    description: allows you to fly
  adminhax.commands.feed:
    default: op
    description: allows you to feed your player to full
  adminhax.commands.other.feed:
    default: op
    description: allows you to feed others to full
  adminhax.commands.heal:
    default: op
    description: allows you to heal to max health
  adminhax.commands.other.heal:
    default: op
    description: allows you to heal others to max health
  adminhax.commands.repair:
    default: op
    description: allows you to repair
  adminhax.commands.other.repair:
    default: op
    description: allows you to repair
  adminhax.commands.repair.hand:
    default: op
    description: allows you to repair your hand
  adminhax.commands.other.repair.hand:
    default: op
    description: allows you to repair others hand
  adminhax.commands.repair.hotbar:
    default: op
    description: allows you to repair your hotbar
  adminhax.commands.other.repair.hotbar:
    default: op
    description: allows you to repair others hotbar
  adminhax.commands.repair.inventory:
    default: op
    description: allows you to repair your inventory
  adminhax.commands.other.repair.inventory:
    default: op
    description: allows you to repair others inventory
  adminhax.commands.repair.armor:
    default: op
    description: allows you to repair your armor
  adminhax.commands.other.repair.armor:
    default: op
    description: allows you to repair others armor
  adminhax.commands.repair.all:
    default: op
    description: allows you to repair everything
  adminhax.commands.other.repair.all:
    default: op
    description: allows you to repair everything
  adminhax.commands.godmode:
    default: op
    description: allows you to godmode
  adminhax.commands.other.godmode:
    default: op
    description: allows you to godmode
  adminhax.commands.godmode.get:
    default: op
    description: allows you to godmode
  adminhax.commands.other.godmode.get:
    default: op
    description: allows you to godmode
